version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    steps:
      - run:
          name: "SSM-Signing"
          command: |
            cd C:\
            echo $SM_API_KEY
            echo "After"
            $env:SM_API_KEY
          # shell: cmd
workflows:
  my-workflow:
    jobs:
      - build