version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  # Certificate_Setup:
  #   executor: win/server-2022
  #   steps:
  #     - run:
  #         name: "Certificate-Setup"
  #         command: |
  #           cd C:\
  #           New-Item C:\CERT_FILE.p12.b64
  #           Set-Content -Path C:\CERT_FILE.p12.b64 -Value $env:SM_CLIENT_CERT_FILE_B64
  #           certutil -decode CERT_FILE.p12.b64 Certificate_pkcs12.p12
  #           cat Certificate_pkcs12.p12
  #   environment:
  #     SM_CLIENT_CERT_FILE: 'C:\Certificate_pkcs12.p12'

  SSM_Signing:
    executor: win/server-2022
    steps:
      - checkout
      - run:
          name: "Certificate-Setup"
          command: |
            dir
            cd C:\
            New-Item C:\CERT_FILE.p12.b64
            Set-Content -Path C:\CERT_FILE.p12.b64 -Value $env:SM_CLIENT_CERT_FILE_B64
            certutil -decode CERT_FILE.p12.b64 Certificate_pkcs12.p12
            cat Certificate_pkcs12.p12
    
      - run:
          name: "SSM-Signing"
          command: |
            dir ~/project/
            cd C:\
            curl.exe -X GET  https://stage.one.digicert.com/signingmanager/api-ui/v1/releases/smtools-windows-x64.msi/download -H "x-api-key:$env:SM_API_KEY" -o smtools-windows-x64.msi
            dir
            msiexec.exe /i smtools-windows-x64.msi /quiet /qn | Wait-Process
            & 'C:\Program Files\DigiCert\DigiCert One Signing Manager Tools\smksp_cert_sync.exe'

      - run:
          name: "Signtool-Signing"
          command: |
            Copy-Item -Path C:\Users\circleci.PACKER-624EE792\project\UNSIGNED.EXE -Destination C:\
            & 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe' sign /sha1 $env:SM_CODE_SIGNING_CERT_SHA1_HASH /tr http://timestamp.digicert.com /td SHA256 /fd SHA256 C:\UNSIGNED.EXE
            & 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe'verify /v /pa C:\UNSIGNED.EXE

      - run:
          name: "Nuget-Signing"
          command: |
            Copy-Item -Path C:\Users\circleci.PACKER-624EE792\project\UNSIGNED.nupkg -Destination C:\
            nuget sign C:\UNSIGNED.nupkg -Timestamper http://timestamp.digicert.com -outputdirectory C:\Signed -CertificateFingerprint $env:SM_CODE_SIGNING_CERT_SHA1_HASH -HashAlgorithm SHA256 -Verbosity detailed -Overwrite
            nuget verify -All C:\Signed\*

      - run:
          name: "Signtool-Signing"
          command: |
            Copy-Item -Path C:\Users\circleci.PACKER-624EE792\project\UNSIGNED1.manifest -Destination C:\
            & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\mage.exe' -sign C:\UNSIGNED1.manifest -CertHash $env:SM_CODE_SIGNING_CERT_SHA1_HASH -a sha256RSA
            & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\mage.exe' -Verify C:\UNSIGNED1.manifest
    environment:
      SM_CLIENT_CERT_FILE: 'C:\Certificate_pkcs12.p12'

workflows:
  my-workflow:
    jobs:
      # - Certificate_Setup
      - SSM_Signing