version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    steps:
      - run:
          name: "SSM-Signing"
          command: |
            cd C:\
            curl.exe -X GET  https://stage.one.digicert.com/signingmanager/api-ui/v1/releases/smtools-windows-x64.msi/download -H "x-api-key:$SM_API_KEY" -o smtools-windows-x64.msi
            dir
            msiexec.exe /i smtools-windows-x64.msi /quiet /qn
            dir 'C:\Program Files\'
          # shell: cmd
workflows:
  my-workflow:
    jobs:
      - build