version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    steps:
      - run:
          command: |
            echo 'Hello world'
            $env:A='aman'
            $env:A
          # shell: cmd
workflows:
  my-workflow:
    jobs:
      - build