version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    steps:
      - run:
          command: |
            echo 'Hello world'
            set A=Aman
            echo %A%
          shell: cmd
workflows:
  my-workflow:
    jobs:
      - build